apiVersion: v2

name: youtrack-ce
description: Meet Youtrack. An open-source software development tool to manage issues, sprints, and product roadmaps with peace of mind.

type: application

version: 1.0.26
appVersion: "0.23.0"

home: https://youtrack.so
icon: https://youtrack.so/favicon/favicon-32x32.png
sources:
  - https://github.com/getyoutrack/youtrack

annotations:
  artifacthub.io/license: AGPL-3.0
